### ISSUE TITLE
Add Fields for Accounts

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Cypher#21]
## TODO

- [ ] Add Fields in the Account
- [ ] Add Optional Field of Adding Recovery Phases
- [ ] Add Additional Key Value Pairs for the Account
